### ISSUE TITLE
Mod interferes with ability to dismiss popups

### ISSUE THREAD

**Issue by Kravchenko32** [Skippeh/SatisfactoryHelper#1]
I can normally open assembler menu with E and then dismiss it with E again. I am forced to use the close button or in some cases I can press E while hovering outside of the popup window. Other popup are also hosed.

**Comment by Skippeh** [comment]
Hi

I've looked into this issue and haven't been able to fix it yet. I'll keep trying though.

**Comment by Ejsstiil** [comment]
Any luck with this? It's a very nice mod and this is kinda deal-breaker ;)

**Comment by Skippeh** [comment]
I've found a fix for this bug finally. I'll release a new version within the next few days.

**Comment by Skippeh** [comment]
Fixed. An update has been released.
