### ISSUE TITLE
Plugin load error

### ISSUE THREAD

**Issue by GezginciTR** [Skippeh/SatisfactoryHelper#3]
While the game is opening, plugin giving error
"Plugin 'SatisfactoryHelper' failed to load because module 'SatisfactoryHelper' could not be found. Plase ensure the plugin is properly installed, otherwise consider the plugin for this project."
Game and sml version: Satisfactory Experimental (Epic Games) - CL 152331 - SML v3.1.0

**Comment by imibion** [comment]
Same here, Steam, EarlyAccess - 0.4.2.2 Build 152331, SML v3.1.0

**Comment by Skippeh** [comment]
I'll release an update asap, probably tomorrow (thursday)

**Comment by Skippeh** [comment]
I released an update. I'm sure it'll work now but just to be sure can you confirm it's fixed?

**Comment by GezginciTR** [comment]
This problem has been fixed, but the client has received a new update and gives a client error while Save load. So let me close this issue and open a new issue.
