### ISSUE TITLE
Save load Unreal Engine Crash

### ISSUE THREAD

**Issue by GezginciTR** [Skippeh/SatisfactoryHelper#4]
When load save or create new game Process giving error,
Game and sml version: Satisfactory Experimental (Epic Games) - CL 153765 - SML v3.1.0

`Version: 153765, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Standalone, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000248

FactoryGame_SatisfactoryHelper_Win64_Shipping!ASHCheatSubsystem::BeginPlay() [D:\UE4_Projects\SatisfactoryMods\SatisfactoryHelper\Plugins\SatisfactoryHelper\Source\SatisfactoryHelper\Private\Subsystems\SHCheatSubsystem.cpp:28]
FactoryGame_Engine_Win64_Shipping!AActor::DispatchBeginPlay() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\actor.cpp:3449]
FactoryGame_Engine_Win64_Shipping!AWorldSettings::NotifyBeginPlay() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\worldsettings.cpp:246]
FactoryGame_FactoryGame_Win64_Shipping!AFGWorldSettings::NotifyBeginPlay() [d:\ws\sb-210421141322-21c\ue4\games\factorygame\source\factorygame\private\fgworldsettings.cpp:228]
FactoryGame_Engine_Win64_Shipping!AGameMode::HandleMatchHasStarted() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\gamemode.cpp:239]
FactoryGame_Engine_Win64_Shipping!AGameMode::SetMatchState() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\gamemode.cpp:355]
FactoryGame_Engine_Win64_Shipping!UWorld::BeginPlay() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\world.cpp:4243]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\unrealengine.cpp:13023]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [d:\ws\sb-210421141322-21c\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:29]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12228]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12426]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\engine\private\gameengine.cpp:1686]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-210421141322-21c\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:13]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4910]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\launch\private\launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll`

**Comment by Skippeh** [comment]
I released an update, should work now. Can you confirm?

**Comment by GezginciTR** [comment]
Works fine thnx
